#!/bin/sh
# Last Update: Jan 09 2020

<< 'CHANGELOG'

1,0 30/07/2021 [ Author: Joelson Salustiano ]
        * Initial release
        * Ambiente do suporte com algumas funções que mais utilizo e algumas adições;
        * Adição das funções:
        * justspam;
        * alertroot;
    
CHANGELOG

# Função principal, listar todas as funções disponíveis
#GitHub



# Função principal, listar todas as funções disponíveis
function supas (){
echo -e "-----------------CODEX-----------------"
echo -e "cmscheck\t\t->\tLista CMS de uma conta"
echo -e "pyscan\t\t\t->\tVarredura numa conta especifica."
echo -e "delfrozen\t\t->\tRemover e-mails frozen da fila"
echo -e "delusermail\t\t->\tRemover e-mails de uma conta da fila"
echo -e "sendmail\t\t->\tEnviar e-mail"
echo -e "mq\t\t\t->\tFila de e-mail para auditoria"
echo -e "spfxuxu\t\t\t->\tRotacionamento de ip by IgorA"
echo -e "justspam\t\t->\tSolicitar delist no JustSpam via e-mail (adicionar destinatário e subject retornados no thunderbird)"
echo -e "ipsaida\t\t\t->\tMostra o IP de saída de e-mails";
echo -e "alertroot\t\t->\tDesabilita notificações do csf";
echo -e "deepmail\t\t->\tGera um relatório completo do envio de e-mails nas últimas 48H\n";}



supas;

#CODEX
alias ls="ls -al --color=always";export LESS="r";
alias cmscheck='bash <(curl -ks https://codesilo.dimenoc.com/pablo.b/cmscheck/raw/master/checkallcms.sh) "$@"';
alias pyscan='bash <(curl -ks http://legal.hostdime.com/tjb_env/run-pyscan.sh) "$@"'
alias spfxuxu='bash <(curl -ks https://gist.githubusercontent.com/igorhrq/ec9f90a71d02adf548cf60e6aaccf006/raw/aa59ebe85243a71f76f364febf16a7ec1df395f4/spfxuxu.sh)'
alias justspam='bash <(curl -ks https://raw.githubusercontent.com/joelsondepaula/joelptmusPrime/main/justspamdelist.sh)'
alias rotacionamentoip='bash <(curl -ks https://raw.githubusercontent.com/Pablocst/scripts/main/fixedrotacionamento.sh)';
alias deepmail="perl <(curl -ks 'https://raw.githubusercontent.com/Pablocst/scripts/main/deepmail.pl') --hours=48 root";



function ipsaida(){

IP_DE_SAIDA=$(cat /etc/exim.conf | grep 'interface' | egrep -o "(((1[0-9]|[1-9]?)[0-9]|2([0-4][0-9]|5[0-5]))\.){3}((1[0-9]|[1-9]?)[0-9]|2([0-4][0-9]|5[0-5]))" | head -n 1)
     if [[ -z $IP_DE_SAIDA ]]; then
        cat /var/cpanel/mainip && echo -e ""
     else
        echo "$IP_DE_SAIDA"

     fi
}

function alertroot(){

sed -i '/PT_USERPROC/s/"[^>]*"/"0"/g' /etc/csf/csf.conf && sed -i '/PT_USERMEM/s/"[^>]*"/"0"/g' /etc/csf/csf.conf && sed 's/To\: root/To\: devnull/g' -i /etc/csf/alerts/* && echo "/dev/null" >> /root/.forward && csf -r && service exim restart

}
