#!/bin/bash


echo -e "$H2 Sender:$RS"
read -p " " MAILS;
echo " "
echo -e "$H2 Recipient:$RS"
read -p " " MAILR;
echo " "
echo -e "$H2 Subject:$RS"
read -p " " SUB;

echo -e "Subject: $SUB" | exim -r "$MAILS" -v -odf "$MAILR"
