#!/bin/bash


archive='msblocklistcheck.txt'
archive2='teste2.txt'
ipsaida=$(hostname -i | tr -s " " | cut -f1 -d " ")


echo "Please contact your Internet service provider since part of their network is on our block list (S3140)" &>> teste2.txt
#echo "TesteHDBR" | exim -r root@$HOSTNAME -v -odf testehostdime@hotmail.com &>> 'msblocklistcheck.txt'

        if grep -iq "Please contact your Internet service provider since part of their network is on our block list (S3140)" "$archive2"; then

                echo "O servidor $HOSTNAME de IP "$ipsaida" está listado na Microsoft SNDS Blocklist" | mail -s "O servidor $HOSTNAME de IP "$ipsaida" está listado na Microsoft SNDS Blocklist" testehostdim$
        else
            	echo "erro"

        fi
