#!/bin/bash


archive='msblocklistcheck.txt'
ipsaida=$(hostname -i | tr -s " " | cut -f1 -d " ")

rm -f msblocklistcheck.txt

echo "TesteHDBR" | exim -r root@$HOSTNAME -v -odf testehostdime@hotmail.com &>> 'msblocklistcheck.txt'

        if grep -iq "Please contact your Internet service provider since part of their network is on our block list" "$archive"; then

                body=$(cat msblocklistcheck.txt)

                echo "$body" | mail -s "HostDime Brasil :: O servidor $HOSTNAME de IP "$ipsaida" está listado na Microsoft SNDS Blocklist" hostdimeteste@gmail.com

        else
            	exit;

        fi
        
rm -f msblocklistcheck.txt
